### ISSUE TITLE
Parallel run on multi android devices 

### ISSUE THREAD

**Issue by RollerIn** [qaschevychelov/JSWebdriverioAutomation#2]
Hello,
can you please help , how can we do configure a file to run tests on multi android devices ? same foe iOS?

am trying from last couple of months but not getting any clue anywhere …and its eating my deadlines….I tried different combination but nolcuk….here am sharing one of the way I have tried 
```
const host = '127.0.0.1';   // default appium host
//const port = 4730;
const path='/wd/hub';
config.capabilities =[
    {
        services: [
            ['appium', {
                args: {
                    debugLogSpacing: true,
                },
                command: 'appium',
            },
            ],
        ],
        specs: [
            "./test/specs/test.spec.js"
        ],
        maxInstances: 2,
    // For iOS/android bases mobile device
        "android":[{
            port: 4723,
            // The defaults you need to have in your config
            "appium:automationName": 'UiAutomator2',
            "appium:deviceName": 'Nexus_30',
            "appium:avd":'Nexus_30',
            platformName: 'Android',
            fullReset: true,
            appPackage: '*',
            appActivity: '*',
            newCommandTimeout: 600,
        },
        {
            port: 4725,
            // The defaults you need to have in your config
            "appium:automationName": 'UiAutomator2',
            "appium:deviceName": 'Nexus_12',
            "appium:avd":'Nexus_12',
            platformName: 'Android',
            fullReset: true,
            appPackage: '*',
            appActivity: '*',
            newCommandTimeout: 600,
        }],
    }];


exports.config = config;
```

**Comment by qaschevychelov** [comment]
Hi RollerIn,

It's been long time. I can only suggest something like the following:
```
require("ts-node").register({files: true});
exports.config = {
    runner: 'local',
    framework: 'mocha',
    sync: true,
    logLevel: 'debug',
    deprecationWarnings: true,
    bail: 0,
    baseUrl: 'http://the-internet.herokuapp.com',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    reporters: ['spec'],

    // ====================
    // Appium Configuration
    // ====================
maxInstances: 4,    
services: [
        [
            'appium',
            {
                args: {
                // For arguments see
                // https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-appium-service
                },
                command: 'appium',
            },
        ],
    ],
    capabilities: {
           port: ???, // here you need to programmatically generate different ports. Two or more threads can not use the same port.
            "appium:automationName": 'UiAutomator2',
            "appium:deviceName": 'Nexus_30',
            "appium:avd":'Nexus_30',
            platformName: 'Android',
            fullReset: true,
            appPackage: '*',
            appActivity: '*',
            newCommandTimeout: 600
    }
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000 * 10
    }
};
```
You can run 4 instances of the same emulator (Nexus_30 as example) and test it out. 
I only ran 2 devices simultaneously within 1 test case (where 1 device send some message and 2 device receive this message in the application)

**Comment by RollerIn** [comment]
Thank you @qaschevychelov for your valuable response.
is there any way to identify free & workable ports? since I have tried with few ports and observed few of them not able to connect.
and do I need to use unique ports for each instance? and same as for device?
or can I use same ports for 4 instances?

One more Imp info: I have run iOS and Android devices ..they launched one after another but after completing test1 on android ..it continued running on iOS….its not parallel...
what I am expecting test1 should run in parallel on both platforms i.e iOS and android

**Comment by qaschevychelov** [comment]
appium uses ports from 4723 etc (4724, 4725...)
So if you have 4 devices (or 4 emulators) you need to start 4 appium servers each with uniq port (first with 4723, second with 4724 etc). As i know WDIO handle running of appium instances by itself. But i dont know how it works under the hood.

About running 1 test on android and iOS devices simultaneously: unfortunately, i didn't have to do such approach. Maybe you can gather all tests into 2 suites? 1 for android and 1 for iOS ?

**Comment by RollerIn** [comment]
```
config.capabilities = [
    {
       
        port: 4723,
        automationName: 'UiAutomator2',
        platformName: 'Android',
        deviceName: AndroidName,
        platformVersion: AndroidVersio,
        orientation: 'PORTRAIT',
        avd: AndroidName,
        browserName: 'chrome',
        acceptInsecureCerts: true,
        'chromeOptions': {
            args: [
                '--no-first-run',
                '--ignore-certificate-errors',
                '--window-size=2600,1800',
                '--allow-http-background-page',
                '--allow-running-insecure-content',
                '--allow-insecure-localhost',
                '--no-sandbox',
                '--disable-dev-shm-usage',
                '--disable-infobars',
                '--disable-web-security',
                '--disable-popup-blocking'
            ],
        },
        newCommandTimeout: 240,
        maxInstances: 1,
    },
    {

        port: 4730,
        automationName: 'XCUITest',
        deviceName: 'iPhone 6',
        platformName: 'iOS',
        platformVersion: '10',
        avd: 'iPhone 6',
        orientation: 'PORTRAIT',
        browserName: 'safari',
        acceptInsecureCerts: true,
        nativeWebTap:true,

        maxInstances: 1,
    },

];

exports.config = config;
```
Te above config ,am running..what is happening..
it launched android and it runs test cases <set of cases> once execution completed then only appium lanced iOS devices and run all test cases 
but wha ti want launch android and iOS devices at a time and run same set of test cases on both devices..but its not happening here…am I missing at aocnfig level?

**Comment by qaschevychelov** [comment]
hmm maybe you need to add `maxInstances: 2` at config level
Now you have `maxInstances` inside `capabilities` array. But what if add  `maxInstances: 2` at level above?
```
config.capabilities =...
config.maxInstances = 2
```

**Comment by RollerIn** [comment]
Yes, you are correct…inside cap …won't work..but outside ..they are working…thank you very much

**Comment by qaschevychelov** [comment]
happy to help!
can i close this ticket?

**Comment by RollerIn** [comment]
I need your experience on WebdriverIO framework maintenance, how did you felt when test cases grows in huge…will it be easy to maintain?
Did you get any chance to work on mobile browsers like firefox, opera, edge on android/iOS?
if yes, can share caps..I tried but did not work

**Comment by RollerIn** [comment]
> happy to help!
> can i close this ticket?

its really …you saved my lot of time….thanks a lot

**Comment by qaschevychelov** [comment]
1. didn't manage to work with mobile browsers. I only know for android that you need to ask android developers to enable `WebView.setWebContentsDebuggingEnabled(true);` in webview in the app source in order you to have ability to change context from native to webview.
2. maintenance depends on project (how often front changes etc), how you create pageObjects. I didnt feel it worse than any other language (java for instance). There were some troubles with debugging. There are debug configurations and plugins but it sucks comparing with java debugger. WDIO supports tags for flexible test run - great feature.

**Comment by RollerIn** [comment]
> * didn't manage to work with mobile browsers. I only know for android that you need to ask android developers to enable `WebView.setWebContentsDebuggingEnabled(true);` in webview in the app source in order you to have ability to change context from native to webview.
> * maintenance depends on project (how often front changes etc), how you create pageObjects. I didnt feel it worse than any other language (java for instance). There were some troubles with debugging. There are debug configurations and plugins but it sucks comparing with java debugger. WDIO supports tags for flexible test run - great feature.

Yes, Debugging is too bad and sucking time…still not understanding why debugging is not improved in WebdriverIO
